// Generated from the Firestore domain schema. Run npm run db:types.
// The public/Tables envelope preserves the application data contract; it does not connect to SQL.
export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];
export type Database = { public: { Tables: {
academic_years: { Row: { id: string; school_id: string; year: number; is_active: boolean; archived_at: string | null; created_at: string; updated_at: string };
Insert: { id?: string; school_id: string; year: number; is_active?: boolean; archived_at?: string | null; created_at?: string; updated_at?: string };
Update: { id?: string; school_id?: string; year?: number; is_active?: boolean; archived_at?: string | null; created_at?: string; updated_at?: string }; Relationships: [] };
attendance_records: { Row: { id: string; attendance_session_id: string; enrollment_id: string; status: string; note: string | null; updated_by: string; created_at: string; updated_at: string };
Insert: { id?: string; attendance_session_id: string; enrollment_id: string; status: string; note?: string | null; updated_by?: string; created_at?: string; updated_at?: string };
Update: { id?: string; attendance_session_id?: string; enrollment_id?: string; status?: string; note?: string | null; updated_by?: string; created_at?: string; updated_at?: string }; Relationships: [] };
attendance_sessions: { Row: { id: string; teacher_assignment_id: string; attendance_date: string; period_number: number; topic: string | null; hours: number; created_by: string; created_at: string; updated_at: string };
Insert: { id?: string; teacher_assignment_id: string; attendance_date: string; period_number?: number; topic?: string | null; hours?: number; created_by?: string; created_at?: string; updated_at?: string };
Update: { id?: string; teacher_assignment_id?: string; attendance_date?: string; period_number?: number; topic?: string | null; hours?: number; created_by?: string; created_at?: string; updated_at?: string }; Relationships: [] };
audit_logs: { Row: { id: string; school_id: string; actor_user_id: string | null; action: string; entity_type: string; entity_id: string | null; before_data: Json | null; after_data: Json | null; metadata: Json; created_at: string };
Insert: { id?: string; school_id: string; actor_user_id?: string | null; action: string; entity_type: string; entity_id?: string | null; before_data?: Json | null; after_data?: Json | null; metadata?: Json; created_at?: string };
Update: { id?: string; school_id?: string; actor_user_id?: string | null; action?: string; entity_type?: string; entity_id?: string | null; before_data?: Json | null; after_data?: Json | null; metadata?: Json; created_at?: string }; Relationships: [] };
characteristic_results: { Row: { id: string; teacher_assignment_id: string; characteristic_id: string; enrollment_id: string; level: number; note: string | null; created_at: string; updated_at: string };
Insert: { id?: string; teacher_assignment_id: string; characteristic_id: string; enrollment_id: string; level: number; note?: string | null; created_at?: string; updated_at?: string };
Update: { id?: string; teacher_assignment_id?: string; characteristic_id?: string; enrollment_id?: string; level?: number; note?: string | null; created_at?: string; updated_at?: string }; Relationships: [] };
classrooms: { Row: { id: string; school_id: string; academic_year_id: string; grade_level_id: string; name: string; room_number: string; homeroom_teacher_id: string | null; active: boolean; created_at: string; updated_at: string };
Insert: { id?: string; school_id: string; academic_year_id: string; grade_level_id: string; name: string; room_number: string; homeroom_teacher_id?: string | null; active?: boolean; created_at?: string; updated_at?: string };
Update: { id?: string; school_id?: string; academic_year_id?: string; grade_level_id?: string; name?: string; room_number?: string; homeroom_teacher_id?: string | null; active?: boolean; created_at?: string; updated_at?: string }; Relationships: [] };
desirable_characteristics: { Row: { id: string; school_id: string; code: string; name: string; sort_order: number; created_at: string; updated_at: string };
Insert: { id?: string; school_id: string; code: string; name: string; sort_order?: number; created_at?: string; updated_at?: string };
Update: { id?: string; school_id?: string; code?: string; name?: string; sort_order?: number; created_at?: string; updated_at?: string }; Relationships: [] };
enrollments: { Row: { id: string; student_id: string; classroom_id: string; academic_year_id: string; student_number: number; status: string; created_at: string; updated_at: string };
Insert: { id?: string; student_id: string; classroom_id: string; academic_year_id: string; student_number: number; status?: string; created_at?: string; updated_at?: string };
Update: { id?: string; student_id?: string; classroom_id?: string; academic_year_id?: string; student_number?: number; status?: string; created_at?: string; updated_at?: string }; Relationships: [] };
final_results: { Row: { id: string; teacher_assignment_id: string; enrollment_id: string; total_score: number; grade: string | null; result_status: string; teacher_note: string | null; calculated_at: string; calculated_by: string; created_at: string; updated_at: string };
Insert: { id?: string; teacher_assignment_id: string; enrollment_id: string; total_score: number; grade?: string | null; result_status?: string; teacher_note?: string | null; calculated_at?: string; calculated_by?: string; created_at?: string; updated_at?: string };
Update: { id?: string; teacher_assignment_id?: string; enrollment_id?: string; total_score?: number; grade?: string | null; result_status?: string; teacher_note?: string | null; calculated_at?: string; calculated_by?: string; created_at?: string; updated_at?: string }; Relationships: [] };
grade_levels: { Row: { id: string; school_id: string; code: string; name: string; sort_order: number; created_at: string; updated_at: string };
Insert: { id?: string; school_id: string; code: string; name: string; sort_order?: number; created_at?: string; updated_at?: string };
Update: { id?: string; school_id?: string; code?: string; name?: string; sort_order?: number; created_at?: string; updated_at?: string }; Relationships: [] };
grading_scales: { Row: { id: string; school_id: string; name: string; min_score: number; max_score: number; grade_value: number; display_grade: string; sort_order: number; created_at: string; updated_at: string };
Insert: { id?: string; school_id: string; name?: string; min_score: number; max_score: number; grade_value: number; display_grade: string; sort_order?: number; created_at?: string; updated_at?: string };
Update: { id?: string; school_id?: string; name?: string; min_score?: number; max_score?: number; grade_value?: number; display_grade?: string; sort_order?: number; created_at?: string; updated_at?: string }; Relationships: [] };
indicator_results: { Row: { id: string; learning_indicator_id: string; enrollment_id: string; result: string; note: string | null; created_at: string; updated_at: string };
Insert: { id?: string; learning_indicator_id: string; enrollment_id: string; result: string; note?: string | null; created_at?: string; updated_at?: string };
Update: { id?: string; learning_indicator_id?: string; enrollment_id?: string; result?: string; note?: string | null; created_at?: string; updated_at?: string }; Relationships: [] };
learning_indicators: { Row: { id: string; teacher_assignment_id: string; code: string; description: string; sort_order: number; created_at: string; updated_at: string };
Insert: { id?: string; teacher_assignment_id: string; code: string; description: string; sort_order?: number; created_at?: string; updated_at?: string };
Update: { id?: string; teacher_assignment_id?: string; code?: string; description?: string; sort_order?: number; created_at?: string; updated_at?: string }; Relationships: [] };
profiles: { Row: { id: string; full_name: string; email: string; avatar_url: string | null; phone: string | null; active: boolean; requested_school_id: string | null; last_login_at: string | null; created_at: string; updated_at: string };
Insert: { id: string; full_name: string; email: string; avatar_url?: string | null; phone?: string | null; active?: boolean; requested_school_id?: string | null; last_login_at?: string | null; created_at?: string; updated_at?: string };
Update: { id?: string; full_name?: string; email?: string; avatar_url?: string | null; phone?: string | null; active?: boolean; requested_school_id?: string | null; last_login_at?: string | null; created_at?: string; updated_at?: string }; Relationships: [] };
reading_assessment_categories: { Row: { id: string; school_id: string; name: string; sort_order: number; created_at: string; updated_at: string };
Insert: { id?: string; school_id: string; name: string; sort_order?: number; created_at?: string; updated_at?: string };
Update: { id?: string; school_id?: string; name?: string; sort_order?: number; created_at?: string; updated_at?: string }; Relationships: [] };
reading_assessment_results: { Row: { id: string; teacher_assignment_id: string; category_id: string; enrollment_id: string; level: number; note: string | null; created_at: string; updated_at: string };
Insert: { id?: string; teacher_assignment_id: string; category_id: string; enrollment_id: string; level: number; note?: string | null; created_at?: string; updated_at?: string };
Update: { id?: string; teacher_assignment_id?: string; category_id?: string; enrollment_id?: string; level?: number; note?: string | null; created_at?: string; updated_at?: string }; Relationships: [] };
school_settings: { Row: { id: string; school_id: string; key: string; value: Json; created_at: string; updated_at: string };
Insert: { id?: string; school_id: string; key: string; value: Json; created_at?: string; updated_at?: string };
Update: { id?: string; school_id?: string; key?: string; value?: Json; created_at?: string; updated_at?: string }; Relationships: [] };
schools: { Row: { id: string; name: string; code: string | null; logo_url: string | null; address: string | null; phone: string | null; director_name: string | null; education_area: string | null; created_at: string; updated_at: string };
Insert: { id?: string; name: string; code?: string | null; logo_url?: string | null; address?: string | null; phone?: string | null; director_name?: string | null; education_area?: string | null; created_at?: string; updated_at?: string };
Update: { id?: string; name?: string; code?: string | null; logo_url?: string | null; address?: string | null; phone?: string | null; director_name?: string | null; education_area?: string | null; created_at?: string; updated_at?: string }; Relationships: [] };
score_categories: { Row: { id: string; teacher_assignment_id: string; name: string; max_score: number; weight: number; sort_order: number; category_type: string; created_at: string; updated_at: string };
Insert: { id?: string; teacher_assignment_id: string; name: string; max_score: number; weight: number; sort_order?: number; category_type?: string; created_at?: string; updated_at?: string };
Update: { id?: string; teacher_assignment_id?: string; name?: string; max_score?: number; weight?: number; sort_order?: number; category_type?: string; created_at?: string; updated_at?: string }; Relationships: [] };
score_items: { Row: { id: string; score_category_id: string; title: string; description: string | null; max_score: number; due_date: string | null; sort_order: number; active: boolean; created_at: string; updated_at: string };
Insert: { id?: string; score_category_id: string; title: string; description?: string | null; max_score: number; due_date?: string | null; sort_order?: number; active?: boolean; created_at?: string; updated_at?: string };
Update: { id?: string; score_category_id?: string; title?: string; description?: string | null; max_score?: number; due_date?: string | null; sort_order?: number; active?: boolean; created_at?: string; updated_at?: string }; Relationships: [] };
student_scores: { Row: { id: string; score_item_id: string; enrollment_id: string; score: number; note: string | null; entered_by: string; created_at: string; updated_at: string };
Insert: { id?: string; score_item_id: string; enrollment_id: string; score: number; note?: string | null; entered_by?: string; created_at?: string; updated_at?: string };
Update: { id?: string; score_item_id?: string; enrollment_id?: string; score?: number; note?: string | null; entered_by?: string; created_at?: string; updated_at?: string }; Relationships: [] };
students: { Row: { id: string; school_id: string; student_code: string; national_student_id: string | null; prefix: string; first_name: string; last_name: string; nickname: string | null; gender: string | null; birth_date: string | null; photo_url: string | null; active: boolean; created_at: string; updated_at: string };
Insert: { id?: string; school_id: string; student_code: string; national_student_id?: string | null; prefix?: string; first_name: string; last_name: string; nickname?: string | null; gender?: string | null; birth_date?: string | null; photo_url?: string | null; active?: boolean; created_at?: string; updated_at?: string };
Update: { id?: string; school_id?: string; student_code?: string; national_student_id?: string | null; prefix?: string; first_name?: string; last_name?: string; nickname?: string | null; gender?: string | null; birth_date?: string | null; photo_url?: string | null; active?: boolean; created_at?: string; updated_at?: string }; Relationships: [] };
subjects: { Row: { id: string; school_id: string; subject_code: string; name: string; subject_group: string | null; hours_per_term: number; credits: number; description: string | null; active: boolean; created_at: string; updated_at: string };
Insert: { id?: string; school_id: string; subject_code: string; name: string; subject_group?: string | null; hours_per_term?: number; credits?: number; description?: string | null; active?: boolean; created_at?: string; updated_at?: string };
Update: { id?: string; school_id?: string; subject_code?: string; name?: string; subject_group?: string | null; hours_per_term?: number; credits?: number; description?: string | null; active?: boolean; created_at?: string; updated_at?: string }; Relationships: [] };
teacher_assignments: { Row: { id: string; school_id: string; teacher_id: string; classroom_id: string; subject_id: string; term_id: string; active: boolean; workflow: 'draft' | 'submitted' | 'approved' | 'locked'; workflow_note: string | null; score_total: number; created_at: string; updated_at: string };
Insert: { id?: string; school_id: string; teacher_id: string; classroom_id: string; subject_id: string; term_id: string; active?: boolean; workflow?: 'draft' | 'submitted' | 'approved' | 'locked'; workflow_note?: string | null; score_total?: number; created_at?: string; updated_at?: string };
Update: { id?: string; school_id?: string; teacher_id?: string; classroom_id?: string; subject_id?: string; term_id?: string; active?: boolean; workflow?: 'draft' | 'submitted' | 'approved' | 'locked'; workflow_note?: string | null; score_total?: number; created_at?: string; updated_at?: string }; Relationships: [] };
teacher_invitations: { Row: { id: string; school_id: string; email: string; role: 'admin' | 'teacher'; status: string; invited_by: string; accepted_by: string | null; expires_at: string; created_at: string; updated_at: string };
Insert: { id?: string; school_id: string; email: string; role?: 'admin' | 'teacher'; status?: string; invited_by: string; accepted_by?: string | null; expires_at?: string; created_at?: string; updated_at?: string };
Update: { id?: string; school_id?: string; email?: string; role?: 'admin' | 'teacher'; status?: string; invited_by?: string; accepted_by?: string | null; expires_at?: string; created_at?: string; updated_at?: string }; Relationships: [] };
terms: { Row: { id: string; academic_year_id: string; term_number: number; name: string; start_date: string; end_date: string; is_active: boolean; created_at: string; updated_at: string };
Insert: { id?: string; academic_year_id: string; term_number: number; name: string; start_date: string; end_date: string; is_active?: boolean; created_at?: string; updated_at?: string };
Update: { id?: string; academic_year_id?: string; term_number?: number; name?: string; start_date?: string; end_date?: string; is_active?: boolean; created_at?: string; updated_at?: string }; Relationships: [] };
user_roles: { Row: { id: string; user_id: string; school_id: string; role: 'admin' | 'teacher'; created_at: string; updated_at: string };
Insert: { id?: string; user_id: string; school_id: string; role: 'admin' | 'teacher'; created_at?: string; updated_at?: string };
Update: { id?: string; user_id?: string; school_id?: string; role?: 'admin' | 'teacher'; created_at?: string; updated_at?: string }; Relationships: [] };
}; Functions: {
manage_member: { Args: {p_school: string; p_user: string; p_role: "admin" | "teacher"; p_active: boolean}; Returns: undefined };
bulk_save_scores: { Args: {p_assignment: string; p_item: string; p_rows: Json}; Returns: undefined };
bulk_score_matrix: { Args: {p_assignment: string; p_items: Json}; Returns: undefined };
bulk_attendance: { Args: {p_assignment: string; p_date: string; p_period: number; p_hours: number; p_topic: string; p_rows: Json}; Returns: string };
bulk_assessments: { Args: {p_assignment: string; p_kind: string; p_category: string; p_rows: Json}; Returns: undefined };
default_score_categories: { Args: {p_assignment: string}; Returns: undefined };
calculate_final_results: { Args: {p_assignment: string}; Returns: undefined };
set_result_status: { Args: {p_assignment: string; p_enrollment: string; p_status: string; p_note: string}; Returns: undefined };
transition_results: { Args: {p_assignment: string; p_state: "draft" | "submitted" | "approved" | "locked"; p_reason: string}; Returns: undefined };
import_students: { Args: {p_classroom: string; p_rows: Json}; Returns: number };
move_student: { Args: {p_enrollment: string; p_classroom: string; p_number: number}; Returns: undefined };
update_student_basics: { Args: {p_student: string; p_prefix: string; p_first: string; p_last: string; p_nickname: string}; Returns: undefined };
log_export: { Args: {p_school: string; p_assignment: string | null; p_kind: string}; Returns: undefined };
assignment_statistics: { Args: {p_assignment: string}; Returns: Json };
}; } };
export type TableName = keyof Database["public"]["Tables"];
export type Row<T extends TableName> = Database["public"]["Tables"][T]["Row"];
